
package producteligibilityservice;

import javax.xml.ws.WebFault;
import com.bcldb.services.common.type.ServiceErrorType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ServiceError", targetNamespace = "http://type.common.services.bcldb.com")
public class ErrorMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServiceErrorType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ErrorMessage(String message, ServiceErrorType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ErrorMessage(String message, ServiceErrorType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.bcldb.services.common.type.ServiceErrorType
     */
    public ServiceErrorType getFaultInfo() {
        return faultInfo;
    }

}
