
package producteligibilityservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ProductEligibilityServiceImpl", targetNamespace = "urn:ProductEligibilityService", wsdlLocation = "file:/C:/dev/workspace/ProductEligibility/ProductEligibilityServiceCommon/src/main/resources/wsdl/ProductEligibility.wsdl")
public class ProductEligibilityServiceImpl
    extends Service
{

    private final static URL PRODUCTELIGIBILITYSERVICEIMPL_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(producteligibilityservice.ProductEligibilityServiceImpl.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = producteligibilityservice.ProductEligibilityServiceImpl.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/dev/workspace/ProductEligibility/ProductEligibilityServiceCommon/src/main/resources/wsdl/ProductEligibility.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/dev/workspace/ProductEligibility/ProductEligibilityServiceCommon/src/main/resources/wsdl/ProductEligibility.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PRODUCTELIGIBILITYSERVICEIMPL_WSDL_LOCATION = url;
    }

    public ProductEligibilityServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductEligibilityServiceImpl() {
        super(PRODUCTELIGIBILITYSERVICEIMPL_WSDL_LOCATION, new QName("urn:ProductEligibilityService", "ProductEligibilityServiceImpl"));
    }

    /**
     * 
     * @return
     *     returns ProductEligibilityService
     */
    @WebEndpoint(name = "ProductEligibilityServiceImplPort")
    public ProductEligibilityService getProductEligibilityServiceImplPort() {
        return super.getPort(new QName("urn:ProductEligibilityService", "ProductEligibilityServiceImplPort"), ProductEligibilityService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductEligibilityService
     */
    @WebEndpoint(name = "ProductEligibilityServiceImplPort")
    public ProductEligibilityService getProductEligibilityServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:ProductEligibilityService", "ProductEligibilityServiceImplPort"), ProductEligibilityService.class, features);
    }

}
