
package producteligibilityservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.bcldb.services.common.EmptyRequestType;
import com.bcldb.services.common.GetVersionResponse;
import com.bcldb.services.eligibilityservice.GetEligibilityByCustomerRequest;
import com.bcldb.services.eligibilityservice.GetEligibilityByCustomerResponse;
import com.bcldb.services.eligibilityservice.GetEligibilityByEffectiveDateRequest;
import com.bcldb.services.eligibilityservice.GetEligibilityByEffectiveDateResponse;
import com.bcldb.services.eligibilityservice.GetEligibilityBySKURequest;
import com.bcldb.services.eligibilityservice.GetEligibilityBySKUResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ProductEligibilityService", targetNamespace = "urn:ProductEligibilityService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.bcldb.services.eligibilityservice.ObjectFactory.class,
    com.bcldb.services.common.type.ObjectFactory.class,
    com.bcldb.services.common.ObjectFactory.class
})
public interface ProductEligibilityService {


    /**
     * 
     * @param part
     * @return
     *     returns com.bcldb.services.common.GetVersionResponse
     * @throws ErrorMessage
     */
    @WebMethod(action = "urn:ProductEligibilityService/getVersionInfo")
    @WebResult(name = "GetVersionResponse", targetNamespace = "http://common.services.bcldb.com", partName = "return")
    public GetVersionResponse getVersionInfo(
        @WebParam(name = "GetVersionInfoRequest", targetNamespace = "http://common.services.bcldb.com", partName = "part")
        EmptyRequestType part)
        throws ErrorMessage
    ;

    /**
     * 
     * @param part
     * @return
     *     returns com.bcldb.services.eligibilityservice.GetEligibilityBySKUResponse
     * @throws ErrorMessage
     */
    @WebMethod(action = "urn:ProductEligibilityService/getEligibilityBySKU")
    @WebResult(name = "GetEligibilityBySKUResponse", targetNamespace = "http://eligibilityservice.services.bcldb.com", partName = "return")
    public GetEligibilityBySKUResponse getEligibilityBySKU(
        @WebParam(name = "GetEligibilityBySKURequest", targetNamespace = "http://eligibilityservice.services.bcldb.com", partName = "part")
        GetEligibilityBySKURequest part)
        throws ErrorMessage
    ;

    /**
     * 
     * @param part
     * @return
     *     returns com.bcldb.services.eligibilityservice.GetEligibilityByCustomerResponse
     * @throws ErrorMessage
     */
    @WebMethod(action = "urn:ProductEligibilityService/getEligibilityByCustomer")
    @WebResult(name = "GetEligibilityByCustomerResponse", targetNamespace = "http://eligibilityservice.services.bcldb.com", partName = "return")
    public GetEligibilityByCustomerResponse getEligibilityByCustomer(
        @WebParam(name = "GetEligibilityByCustomerRequest", targetNamespace = "http://eligibilityservice.services.bcldb.com", partName = "part")
        GetEligibilityByCustomerRequest part)
        throws ErrorMessage
    ;

    /**
     * 
     * @param part
     * @return
     *     returns com.bcldb.services.eligibilityservice.GetEligibilityByEffectiveDateResponse
     * @throws ErrorMessage
     */
    @WebMethod(action = "urn:ProductEligibilityService/getEligibilityByEffectiveDate")
    @WebResult(name = "GetEligibilityByEffectiveDateResponse", targetNamespace = "http://eligibilityservice.services.bcldb.com", partName = "return")
    public GetEligibilityByEffectiveDateResponse getEligibilityByEffectiveDate(
        @WebParam(name = "GetEligibilityByEffectiveDateRequest", targetNamespace = "http://eligibilityservice.services.bcldb.com", partName = "part")
        GetEligibilityByEffectiveDateRequest part)
        throws ErrorMessage
    ;

}
